services:
  mysql:
    image: mysql:8.0
    container_name: personal_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_website
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    container_name: personal_backend
    build:
      context: ./backend
    restart: always
    env_file:
      - .env   # 👈 👈 👈 ESSENCIAL
    environment:
      DB_HOST: mysql
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: personal_website
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  frontend:
    container_name: personal_frontend
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mysql_data: